#pragma once
#include <algorithm>
#include <array>
#include <chrono>
#include <deque>
#include <fstream>
#include <iostream>
#include <locale>
#include <map>
#include <memory>
#include <numeric>
#include <ostream>
#include <queue>
#include <set>
#include <span>
#include <stack>
#include <string>
#include <sstream>
#include <variant>
#include <vector>